# Generated by Django 2.0.4 on 2018-05-06 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.IntegerField(verbose_name=[(1, 'python之路'), (2, '从删库到跑路'), (3, '从入门到放弃'), (4, '皮皮虾我们走'), (5, '程虎好好哦')]),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
